use_frameworks!

platform :ios, '13.0'

target 'QuickDialogScript_Example' do
  #pod 'QuickDialogScript', :path => '../'
  pod 'QuickDialogScript', :git => 'https://github.com/ShiratoriAoi/QuickDialogScript.git'

  target 'QuickDialogScript_Tests' do
    inherit! :search_paths

    
  end
end
