use_frameworks!

platform :ios, '13.0'

target 'QuickDialogScript_Example' do
  pod 'QuickDialogScript', :path => '../'

  target 'QuickDialogScript_Tests' do
    inherit! :search_paths

    
  end
end
